### ISSUE TITLE
Mark parameters as optional.

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/remark-api#6]
I just gave this project a try for [`estree-util-value-to-estree`](https://github.com/remcohaszing/estree-util-value-to-estree) (not committed).

This generates the following information for parameters:

```markdown
### `valueToEstree(value, options)`

Convert a value to an ESTree node.

###### Parameters

- `value` (`unknown`) — the value to convert
- `options` (`Options | undefined`) — additional options to configure the output
```

`options` is optional. `| undefined` kind of gives it away, but it’s not accurate. I would expect something like this:

```markdown
### `valueToEstree(value[, options])`

Convert a value to an ESTree node.

###### Parameters

- `value` (`unknown`) — the value to convert
- `options` (`Options`, optional) — additional options to configure the output
```

or:

```markdown
### `valueToEstree(value, options?)`

Convert a value to an ESTree node.

###### Parameters

- `value` (`unknown`, required) — the value to convert
- `options` (`Options`) — additional options to configure the output
```

**Comment by wooorm** [comment]
Please see https://github.com/wooorm/module-exports/issues/2, https://github.com/wooorm/module-exports/issues/3

**Comment by remcohaszing** [comment]
Ah yes, this is a duplicate of https://github.com/wooorm/module-exports/issues/3
